name: EnShan Signin

on:
  schedule:
    #  每周1运行一次，已经能达到“保活”目的，又不会太频繁
    - cron: '20 20 * * 1'
  workflow_dispatch:   # 保留手动触发，方便你随时调试

jobs:
  signin:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        pip install DrissionPage requests
        
    - name: Run sign-in
      env:
        EST_USER_UID: ${{ secrets.EST_USER_UID }}
        EST_cookie: ${{ secrets.EST_cookie }}
      run: |
        python enshan_sign.py
